version: "3.8"
services:
  db:
    image: "postgres:latest"
    restart: always
    container_name: "postgresContainer"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=viadb
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password

  backend:
    image: "tabloid_backend:latest"
    build:
      context: ./
    container_name: "backend_container"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/viadb
      - SPRING_DATASOURCE_USERNAME=user1
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.hibernate.show-sql=true

#  kubernetes-container:
#    image: kubernete-image:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    volumes:
#      - /data/kubernetes-app
#    ports:
#      - "8080:8080"

volumes:
  data:
    driver: local
