version: "3.8"
services:
  db:
    image: "postgres:latest"
    restart: always
    container_name: "postgres-Container"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tabloid_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend:
    image: "backend-tabloid:latest"
    build:
      context: ./
    container_name: "backend-container"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.jpa.hibernate.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update

volumes:
  db:
    driver: local
